### ISSUE TITLE
TODO: Consider final title for application

### ISSUE THREAD

**Issue by Yuleblinker** [Wintergatan/Midi-to-laser-cutter#10]
I am concerned that using the term '**laser cutter**' throughout the application and in it's title is going to be a bit 'exclusive'. I know the initial brief for the project was to be able to laser cut the music sheets but it is clear from the Google Photos submissions that others wish to use other techniques for creating the holes. Personally I want to eventually use GCode and create the holes with a CNC punch. Others will want to use vinyl or craft cutters. Others will simply want a way of printing out a file to paper and manually punching the holes.

I don't own a laser cutter but can access one. Most people don't own laser cutters and many do not have, or cannot, access one. If the project uses 'Laser Cutter' throughout it may be overlooked or people may be unwilling to investigate it further if they believe they have to use a laser cutter. Of course, the documentation for the project can explain that the files can be used with other devices but someone stumbling across the project may not even bother getting to the documentation if they believe a laser cutter is necessary.

I'm not suggesting this as the title but something along the lines of 'MIDI to Music Strip' may be more descriptive and inviting.

Also, the final application may include the ability to create music tracks directly within the browser (along the lines of the Musicboxmaniacs create tool) and, if this is the case, what might bring people to it may not be the desire/need to 'cut' strips but to enjoy the process of creating a track and simply printing it to punch it. Maybe 'Music Strip Maker' would then be more appropriate.

I know the choice of title isn't really crucial but It may be worth considering.

**Comment by ChemiCalChems** [comment]
Yeah, you are right. MIDI to Music Strip sounds good.

**Comment by DrSkunk** [comment]
MIDI to world?

**Comment by paternoe** [comment]
Midi-to-Music Box Mapper?

**Comment by Wintergatan2000** [comment]
Adding some suggestions:

MIDI to Music Box Strip
MIDI to Music Box Hole Card
MIDI to Music Box

**Comment by Wintergatan2000** [comment]
MIDI to Music Box Paper Strip

OR If we want it more universal:

MIDI to analogue programming punch card strip
MIDI to Punch Card Strip
MIDI to Musical Punch Card Strip for music boxes and more

**Comment by Wintergatan2000** [comment]
MIDI 2 Punch Card
I Kind of like this aswell:

MIDI to Paper Strip for the 20 & 30-Note Music Box Set

That is very descriptive and will do well in SEO because of the 20 - 30 music box set which is what these music boxes are called when they are sold

**Comment by Wintergatan2000** [comment]
"Music Strip Maker" as suggested by yuleblinker Has a very good ring to it! Would be fun if the name was somewhat catchy...

BUT a google search on music strip has nothing to do with punch cards at all... so thats not maybe the best term

**Comment by Wintergatan2000** [comment]
Midi-to-Music Box hole card maker

Sorry for spamming this thread, i cant stop thinking of a good solution here...

**Comment by DrSkunk** [comment]
Maybe ask in your video on Wednesday for a good suggestion?

**Comment by DrSkunk** [comment]
Midibox

**Comment by t-vanasseldonk** [comment]
How about "The Magical MIDI Music Box Generator"?
I feel like I'm not really entitled to name a project I had nothing to do with, but since a call for suggestions was made in the video I feel like I should leave my suggestion here rather than on the video so it doesn't get lost in all the YouTube comments.

**Comment by Lars-Kristian** [comment]
Naming is one of the hardest ting in software development. We need all the help we can get. :)

**Comment by TheInitializer** [comment]
I guess MIDI-to-SVG is a bit boring...

**Comment by djflorio** [comment]
A few commenters on the new video have brought up MIDIPunch, which is kind of cool, though as already mentioned not everyone will be "punching" the holes.

Others off the top of my head:
- MIDIMapper
- NoteCutter
- Notes2Dots
- ScoreStrip

**Comment by epicabsol** [comment]
TurboPunch?
TurboStrip?

**Comment by rokyed** [comment]
Holerama? Holarama? Like Futurama but with holes :smile:

**Comment by benbrandt22** [comment]
Personally I think the name itself can be short, which makes it easier to refer to in discussion, and the details like "midi to paper strip cutout, etc..." can be added as a subheading in written documents.

So I'll offer up a few short options...

Midi Cut / MidiCut
Midi Punch
Midi Make
Midi Fab

or something really abstract... "Colander" ?   :-)

As a software dev and hardware tinkerer, I really like what you all are doing here!

**Comment by EthanRutherford** [comment]
Perhaps MidiLaser, MidiPrint, or something similar, such as those suggested by @benbrandt22 above.
Good software titles are typically a balance between descriptive and succinct, and above all memorable.

**Comment by nommyde** [comment]
**Midi Punch** is good name

**Comment by Lars-Kristian** [comment]
I like something like Midi2Paper or Midi to Paper.
* Short 
* Descriptive
* Few hits on google

**Comment by kenb0t** [comment]
MIDI media converter
multiMIDIa converter
or just multiMIDIa

**Comment by mymaestro** [comment]
Mobius Rift!

**Comment by Wintergatan2000** [comment]
MidiPaper?

Midi Punch has alot going for it, catchy, nice ring to it.

/\/\artin & \/\/intergatan

Follow our progress on Marble Machine X and our Double Album at our Youtube
Channel:

https://www.youtube.com/user/wintergatan2000/videos
<https://www.youtube.com/watch?v=IvUU8joBb1Q>

Download our music Digitally:

https://wintergatan.bandcamp.com/

www.wintergatan.net


2017-05-14 5:09 GMT+02:00 Warren Gill <notifications@github.com>:

**Comment by Yuleblinker** [comment]
Hi Martin. Is that your final decision for the name? Midi Punch. That's okay if it is but does 'punching' for folk who use MIDI a lot have a different meaning? Punch In and Punch Out. Also doing a search for Midi Punch gives pages of results for a lot of stuff to do with _punching in_ and other resources. It might be a bit confusing.

**Comment by Wintergatan2000** [comment]
Not final and i think the decision is more in the hands of you who have developed it! 

/\/\artin & \/\/intergatan

Watch Wintergatan Live @ Roskilde Festival 2013 at www.wintergatan.net
Sommarfågel video - https://www.youtube.com/watch?v=SBK2AF-NdVA
Starmachine2000 video - https://www.youtube.com/watch?v=rEeiRXOlWUE
If you like it, help us spread the word!

**Comment by EthanRutherford** [comment]
Midi-zap/midi-zapper have a similar feel to them as midipunch.

**Comment by weirdsound** [comment]
"Book music" is probably the term you're looking for.
*midi2bookmusic* could be a name for it.

**Comment by TheInitializer** [comment]
>Midi-zap/midi-zapper have a similar feel to them as midipunch.

Ooh, I like this.

**Comment by DrSkunk** [comment]
Final poll to choose the name. The reason I omitted MidiBox is because it's already a popular name and used for a different product.

[![](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BMXJ4FR3FTMVVAG646EX2KGM/MidiPunch)](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BMXJ4FR3FTMVVAG646EX2KGM/MidiPunch/vote)
[![](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BMXJ4FR3FTMVVAG646EX2KGM/Music%20Strip%20Maker)](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BMXJ4FR3FTMVVAG646EX2KGM/Music%20Strip%20Maker/vote)
[![](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BMXJ4FR3FTMVVAG646EX2KGM/Midi-to-Music%20Box%20hole%20card%20maker)](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BMXJ4FR3FTMVVAG646EX2KGM/Midi-to-Music%20Box%20hole%20card%20maker/vote)
[![](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BMXJ4FR3FTMVVAG646EX2KGM/MIMICS%20(Midi%20Into%20Musicbox%20Internet%20Conversion%20Software))](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BMXJ4FR3FTMVVAG646EX2KGM/MIMICS%20(Midi%20Into%20Musicbox%20Internet%20Conversion%20Software)/vote)
[![](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BMXJ4FR3FTMVVAG646EX2KGM/ChopIN%20)](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BMXJ4FR3FTMVVAG646EX2KGM/ChopIN%20/vote)
[![](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BMXJ4FR3FTMVVAG646EX2KGM/DiTTY%20)](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BMXJ4FR3FTMVVAG646EX2KGM/DiTTY%20/vote)

**Comment by DrSkunk** [comment]
MIDIPunch was chosen.
